version: '3.2'
services:
  web-app:
    image: "amyassist/amy-web"
    environment:
      - SERVER_NAME=web-app
  master-node:
    image: "amyassist/amy:dev"
    depends_on:
     - broker
     - database
    volumes:
     - ./config:/config
    environment:
      - AMY_SERVER_CONFIG_SERVER_URL=${AMY_URL}/rest
      - AMY_SOCKET_CONFIG_WEBSOCKETURL=${AMY_WEBSOCKET_URL}/chat
      - AMY_MQTT_CONFIG_BROKER_HOST=tcp://broker
      - AMY_JAVAX_PERSISTENCE_JAVAX_PERSISTENCE_JDBC_URL=jdbc:mysql://database/{databasename}?createDatabaseIfNotExist=true
      - AMY_JAVAX_PERSISTENCE_JAVAX_PERSISTENCE_JDBC_USER=root
      - AMY_JAVAX_PERSISTENCE_JAVAX_PERSISTENCE_JDBC_PASSWORD=sqlrootpassword
      - TZ=$LOCAL_TIMEZONE
  proxy:
    build: ./proxy
    environment:
      - SERVER_NAME=proxy
    ports:
     - "80:80"
     - "443:443"
  broker:
    image: eclipse-mosquitto
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "sqlrootpassword"
    volumes:
     - db-data:/var/lib/mysql
volumes:
  db-data:
